/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainScreen.java
 *
 * Created on Oct 16, 2014, 4:11:07 PM
 */

package ui;

import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JPanel;
import util.AppContext;
import static util.AppContext.* ;


public class MainScreen extends javax.swing.JFrame {

    //public static Container content = null;

    /** Creates new form MainScreen */

    JPanel component = null ;
    int compType = -1 ;
    public MainScreen() {
        initComponents();
        //content = this.getContentPane();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        if(AppContext.CURRENT_LOGIN == AppContext.USER_TYPE_CUSTOMER){
            userMenu.setVisible(false);
            dvdMenu.setVisible(false);
        }


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        mnuItmPrint = new javax.swing.JMenuItem();
        userMenu = new javax.swing.JMenu();
        mnuItmAddUser = new javax.swing.JMenuItem();
        mnuItmEditUser = new javax.swing.JMenuItem();
        mnuItmDeleteUser = new javax.swing.JMenuItem();
        dvdMenu = new javax.swing.JMenu();
        mnuItmAddDVD = new javax.swing.JMenuItem();
        mnuItmEditDVD = new javax.swing.JMenuItem();
        mnuItmDeleteDVD = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItemSearch = new javax.swing.JMenuItem();
        menuItemRentDvd = new javax.swing.JMenuItem();
        menuItemReturnDvd = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DVD Rental Management System");
        setBounds(new java.awt.Rectangle(0, 0, 800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        fileMenu.setText("File");
        fileMenu.setName("fileMenu"); // NOI18N

        mnuItmPrint.setText("Exit");
        mnuItmPrint.setName("mnuItmPrint"); // NOI18N
        mnuItmPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmPrintActionPerformed(evt);
            }
        });
        fileMenu.add(mnuItmPrint);

        jMenuBar1.add(fileMenu);

        userMenu.setText("User");
        userMenu.setName("userMenu"); // NOI18N
        userMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMenuMouseClicked(evt);
            }
        });

        mnuItmAddUser.setText("Add User");
        mnuItmAddUser.setName("mnuItmAddUser"); // NOI18N
        mnuItmAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmAddUserActionPerformed(evt);
            }
        });
        userMenu.add(mnuItmAddUser);

        mnuItmEditUser.setText("Edit User");
        mnuItmEditUser.setName("mnuItmEditUser"); // NOI18N
        mnuItmEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmEditUserActionPerformed(evt);
            }
        });
        userMenu.add(mnuItmEditUser);

        mnuItmDeleteUser.setText("Delete User");
        mnuItmDeleteUser.setName("mnuItmDeleteUser"); // NOI18N
        mnuItmDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmDeleteUserActionPerformed(evt);
            }
        });
        userMenu.add(mnuItmDeleteUser);

        jMenuBar1.add(userMenu);

        dvdMenu.setText("DVD");
        dvdMenu.setName("dvdMenu"); // NOI18N
        dvdMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dvdMenuMouseClicked(evt);
            }
        });

        mnuItmAddDVD.setText("Add DVD");
        mnuItmAddDVD.setName("mnuItmAddDVD"); // NOI18N
        mnuItmAddDVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmAddDVDActionPerformed(evt);
            }
        });
        dvdMenu.add(mnuItmAddDVD);

        mnuItmEditDVD.setText("Edit DVD");
        mnuItmEditDVD.setName("mnuItmEditDVD"); // NOI18N
        mnuItmEditDVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmEditDVDActionPerformed(evt);
            }
        });
        dvdMenu.add(mnuItmEditDVD);

        mnuItmDeleteDVD.setText("Delete DVD");
        mnuItmDeleteDVD.setName("mnuItmDeleteDVD"); // NOI18N
        mnuItmDeleteDVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmDeleteDVDActionPerformed(evt);
            }
        });
        dvdMenu.add(mnuItmDeleteDVD);

        jMenuBar1.add(dvdMenu);

        jMenu1.setText("Rental");
        jMenu1.setName("jMenu1"); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        menuItemSearch.setText("Search DVD");
        menuItemSearch.setName("menuItemSearch"); // NOI18N
        menuItemSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSearchActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemSearch);

        menuItemRentDvd.setText("Rent DVD");
        menuItemRentDvd.setName("menuItemRentDvd"); // NOI18N
        menuItemRentDvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRentDvdActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemRentDvd);

        menuItemReturnDvd.setText("Return DVD");
        menuItemReturnDvd.setName("menuItemReturnDvd"); // NOI18N
        menuItemReturnDvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReturnDvdActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemReturnDvd);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItmAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmAddUserActionPerformed
        showForm(FORM_TYPE_USER_ADD);
        // TODO add your handling code here:
        /*BorderLayout layout = new BorderLayout();
        Container content = this.getContentPane();
        content.removeAll();
        content.setLayout(layout);
        content.add(new TitlePanel(), BorderLayout.NORTH);
        component = new SubpoenaEntryForm();
        compType = AppContext.FORM_TYPE_SUBPOENA;
        content.add(component, BorderLayout.CENTER);
        this.pack();
        this.setVisible(true);*/
    }//GEN-LAST:event_mnuItmAddUserActionPerformed

    public void clearScreen(){
        Container content = this.getContentPane();
        content.removeAll();
        content.setLayout(new BorderLayout());
        content.add(new TitlePanel(), BorderLayout.NORTH);
        content.add(new JPanel(), BorderLayout.CENTER);
        pack();
        setVisible(true);
    }

    
    private void mnuItmEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmEditUserActionPerformed
        showForm(FORM_TYPE_USER_EDIT);
        // TODO add your handling code here:
        /*BorderLayout layout = new BorderLayout();
        Container content = this.getContentPane();
        content.removeAll();
        content.setLayout(layout);
        content.add(new TitlePanel(), BorderLayout.NORTH);
        component = new CivilEntryForm();
        compType = AppContext.FORM_TYPE_CIVIL;
        content.add(component, BorderLayout.CENTER);
        this.pack();
        this.setVisible(true);
         * */

    }//GEN-LAST:event_mnuItmEditUserActionPerformed

    private void mnuItmDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmDeleteUserActionPerformed
        showForm(FORM_TYPE_USER_DELETE);
        // TODO add your handling code here:
        /*BorderLayout layout = new BorderLayout();
        Container content = this.getContentPane();
        content.removeAll();
        content.setLayout(layout);
        content.add(new TitlePanel(), BorderLayout.NORTH);
        component = new WarrantEntryForm();
        compType = FORM_TYPE_WARRANT;

        content.add(component, BorderLayout.CENTER);
        this.pack();
        this.setVisible(true);*/
    }//GEN-LAST:event_mnuItmDeleteUserActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
      //  AppContext.dao.closeDBConnection();
    }//GEN-LAST:event_formWindowClosing

    private void showForm(int formType){
        // TODO add your handling code here:
        BorderLayout layout = new BorderLayout();
        Container content = this.getContentPane();
        content.removeAll();
        content.setLayout(layout);
        content.add(new TitlePanel(), BorderLayout.NORTH);

        //System.out.println(" Setting " + AppContext.FORM_NAME[formType]);
        switch(formType){
            case FORM_TYPE_DVD_ADD:
                component = new AddDVD();
                break;
            case FORM_TYPE_DVD_EDIT:
                component = new UpdateDVD();
                break;
            case FORM_TYPE_DVD_DELETE:
                component = new DeleteDVD();
                break;
            case FORM_TYPE_DVD_SEARCH:
                component = new SearchDVD();
                break;
            case FORM_TYPE_DVD_RENT:
                component = new RentDVD();
                break;
            case FORM_TYPE_DVD_RETURN:
                component = new ReturnDVD();
                break;
            case FORM_TYPE_USER_ADD:
                component = new AddUser();
                break;
            case FORM_TYPE_USER_EDIT:
                component = new UpdateUser();
                break;
            case FORM_TYPE_USER_DELETE:
                component = new DeleteUser();
                break;
        }
        compType = formType;
        content.add(component, BorderLayout.CENTER);
        this.pack();
        this.setVisible(true);
    }




    private void mnuItmPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmPrintActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuItmPrintActionPerformed

    private void mnuItmAddDVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmAddDVDActionPerformed
        showForm(FORM_TYPE_DVD_ADD);
    }//GEN-LAST:event_mnuItmAddDVDActionPerformed

    private void mnuItmEditDVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmEditDVDActionPerformed
        showForm(FORM_TYPE_DVD_EDIT);
    }//GEN-LAST:event_mnuItmEditDVDActionPerformed

    private void dvdMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dvdMenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dvdMenuMouseClicked

    private void userMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_userMenuMouseClicked

    private void mnuItmDeleteDVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmDeleteDVDActionPerformed
        showForm(FORM_TYPE_DVD_DELETE);
    }//GEN-LAST:event_mnuItmDeleteDVDActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void menuItemRentDvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRentDvdActionPerformed
        // TODO add your handling code here:
        showForm(FORM_TYPE_DVD_RENT);
    }//GEN-LAST:event_menuItemRentDvdActionPerformed

    private void menuItemReturnDvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReturnDvdActionPerformed
        // TODO add your handling code here:
        showForm(FORM_TYPE_DVD_RETURN);
    }//GEN-LAST:event_menuItemReturnDvdActionPerformed

    private void menuItemSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSearchActionPerformed
        // TODO add your handling code here:
        showForm(FORM_TYPE_DVD_SEARCH);
    }//GEN-LAST:event_menuItemSearchActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu dvdMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuItemRentDvd;
    private javax.swing.JMenuItem menuItemReturnDvd;
    private javax.swing.JMenuItem menuItemSearch;
    private javax.swing.JMenuItem mnuItmAddDVD;
    private javax.swing.JMenuItem mnuItmAddUser;
    private javax.swing.JMenuItem mnuItmDeleteDVD;
    private javax.swing.JMenuItem mnuItmDeleteUser;
    private javax.swing.JMenuItem mnuItmEditDVD;
    private javax.swing.JMenuItem mnuItmEditUser;
    private javax.swing.JMenuItem mnuItmPrint;
    private javax.swing.JMenu userMenu;
    // End of variables declaration//GEN-END:variables

}
